"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              minimal init.vim                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set shell=/bin/bash


set runtimepath+=~/.vim/bundle/Vundle.vim
set runtimepath+=~/.config/nvim/plugins/deoplete.nvim
let g:deoplete#enable_at_startup = 1

set nocompatible              " be iMproved, required
filetype off                  " required

" Clipbord
set clipboard+=unnamedplus  " use clipboard ( see : help clipboard )

" Mouse ( see :help mouse-using )
set mouse=nvic


call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
Plugin 'VundleVim/Vundle.vim'

Plugin 'roxma/nvim-yarp'
Plugin 'Shougo/deoplete.nvim'

Plugin 'ternjs/tern_for_vim'
"Bundle 'lepture/vim-jinja'

Plugin 'morhetz/gruvbox'
"Plugin 'digitaltoad/vim-pug'

Plugin 'bling/vim-airline'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'Raimondi/delimitMate'
"Plugin 'mileszs/ack.vim'
Plugin 'majutsushi/tagbar'
Plugin 'easymotion/vim-easymotion'
Plugin 'tpope/vim-fugitive'
"Plugin 'craigemery/vim-autotag'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'rking/ag.vim'
"Plugin 'sjl/splice.vim'

Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'mhartington/nvim-typescript'
Plugin 'HerringtonDarkholme/yats.vim'
Plugin 'elmcast/elm-vim'
Plugin 'nvie/vim-flake8'
Plugin 'flowtype/vim-flow'
Plugin 'jparise/vim-graphql'
Plugin 'prettier/vim-prettier'
"Plugin 'toyamarinyon/vim-swift'
"Plugin 'cakebaker/scss-syntax.vim'
"Plugin 'leafgarland/typescript-vim'

"Plugin 'wakatime/vim-wakatime'

"Plugin 'terryma/vim-multiple-cursors'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
call deoplete#enable()

let g:airline#extensions#branch#enabled = 1

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
syntax enable

set shiftwidth=2
set tabstop=2
set softtabstop=2
set autoindent
set copyindent
set expandtab
set noro

set ignorecase
set smartcase

set laststatus=2

let g:airline#extensions#tabline#enabled = 1

set rnu

set wrap

" Leader = ,
let mapleader = ","
" }}}
" ##### General mappings  {{{
" ##### Tabs {{{
nnoremap <leader>c :tabclose<cr>
nnoremap <leader>n :tabnext<cr>
nnoremap <leader>m :tabprevious<cr>
" }}}
" ##### Fzf {{{
noremap <silent> <leader>f :Files<CR>
noremap <silent> <leader>g :GFiles<CR>
noremap <silent> <leader>O :Tags<CR>
noremap <silent> <leader>t :BTags<CR>
noremap <silent> <leader>b :Buffers<CR>
noremap <silent> <leader>? :History<CR>

noremap <silent> <leader>gl :Commits<CR>
noremap <silent> <leader>ga :BCommits<CR>

" }}}

" Go to start of line with H and to the end with $
noremap H ^
noremap L $

" Easy buffer navigation
nnoremap gn :bn<CR>
nnoremap gp :bp<CR>
nnoremap gd :bw<CR>

nmap <S-Enter> O<Esc>

colorscheme gruvbox
let g:gruvbox_contrast_dark='hard'
set background=dark

set relativenumber

" tell it to use an undo file
set undofile
set undodir=~/.vimundo/

" Supress warning when moving out from unsaved buffers
set hidden

" NERDTree Maps
map <C-n> :NERDTreeToggle<CR>
map <C-j> :NERDTreeFind<CR>

let g:multi_cursor_use_default_mapping=0
" Default mapping
let g:multi_cursor_next_key='<C-l>'
let g:multi_cursor_prev_key='<C-h>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

" Commenting out easily
map <D-/> <leader>ci

" Supress warning when reloading file
setl autoread

let g:jsx_ext_required = 0

" Map for tagbar
nmap <F8> :TagbarToggle<CR>

" Ctags mapping
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>
map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

syntax enable

let g:Tlist_Ctags_Cmd='/usr/local/bin/ctags'

let g:flow#enable = 0

set timeoutlen=1000 ttimeoutlen=0

if filereadable('.vimrclocal')
  so .vimrclocal
endif
